Repository geek-cookbook/charts, pull requests merged in 2023-01, with the labels that each got.

#6 Fix Contributor Profile badge Link
  README.md
Labels: size/XS

#12 Add-mlflow
  charts/stable/mlflow/Chart.yaml
  charts/stable/mlflow/values.yaml
Labels: size/XS

#13 Minor fix to action
  .github/workflows/schedule-sync-labels.yaml
Labels: size/XS

#10 Update external dependency minor (minor)
  charts/incubator/dendrite/Chart.yaml
  charts/stable/anonaddy/Chart.yaml
  charts/stable/baikal/Chart.yaml
  charts/stable/bookstack/Chart.yaml
  charts/stable/dnsmadeeasy-webhook/Chart.yaml
  charts/stable/dsmr-reader/Chart.yaml
  charts/stable/firefly-iii/Chart.yaml
  charts/stable/ghost/Chart.yaml
  charts/stable/home-assistant/Chart.yaml
  charts/stable/icinga2/Chart.yaml
  charts/stable/joplin-server/Chart.yaml
  charts/stable/kanboard/Chart.yaml
  charts/stable/maddy/Chart.yaml
  charts/stable/miniflux/Chart.yaml
  charts/stable/monica/Chart.yaml
  charts/stable/openemr/Chart.yaml
  charts/stable/openkm/Chart.yaml
  charts/stable/paperless/Chart.yaml
  charts/stable/photoprism/Chart.yaml
  charts/stable/privatebin/Chart.yaml
  charts/stable/seafile/Chart.yaml
  charts/stable/shlink/Chart.yaml
  charts/stable/statping/Chart.yaml
  charts/stable/teedy/Chart.yaml
  charts/stable/teslamate/Chart.yaml
  charts/stable/tt-rss/Chart.yaml
  charts/stable/unifi-poller/Chart.yaml
  charts/stable/vaultwarden/Chart.yaml
  charts/stable/vikunja/Chart.yaml
  charts/stable/wallabag/Chart.yaml
  charts/stable/webtrees/Chart.yaml
Labels: type/minor, size/M

#8 Update dependency GitPython to v3.1.30
  .github/scripts/requirements.txt
Labels: size/XS

#11 [anonaddy] Update Helm chart redis to v17
  charts/stable/anonaddy/Chart.yaml
Labels: size/XS, type/major

#14 Update dependency pry to v0.14.2
  Gemfile
Labels: size/XS
